### ISSUE TITLE
Global Database

### ISSUE THREAD

**Issue by BennerLukas** [BennerLukas/Tracer#11]
We can host a databse on lumay.eu for testing purposes.

If its not to large (which is not the case)

@Madhour would this be suitable? Or should we continue with a json-file because we dont have a serverbackend anyway?

**Comment by Madhour** [comment]
Let's do it! I think a DB might make things a bit easier. I will postpone the development for processes 2-4 until the DB is up.

**Comment by BennerLukas** [comment]
db is up.

**Comment by Madhour** [comment]
Hosting provider denied access. Implemented a local mysql db instead.
