### ISSUE TITLE
Dynamic navbar 

### ISSUE THREAD

**Issue by Madhour** [BennerLukas/Tracer#22]
**Describe the bug**
Navbar is scrollable on the "create_event" page.

**To Reproduce**
1. start .vue app
2. click on "event" in the lower right

**Expected behavior**
Navbar should be static and always visible.

**Screenshots**
<img width="378" alt="image" src="https://user-images.githubusercontent.com/69970159/107157784-5e168380-6986-11eb-9d8d-588fc43283ba.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 6

**Comment by lukasbach00** [comment]
![image](https://user-images.githubusercontent.com/67925016/107288172-4d880b00-6a63-11eb-84dd-e98e851ba0e5.png)
added "fixed" and "app" to the <v-bottom-navigation> component.
