### ISSUE TITLE
Navbar shows multiple clicked buttons

### ISSUE THREAD

**Issue by Madhour** [BennerLukas/Tracer#23]
**Describe the bug**
Navbar shows that the home button is clicked although the scan page is open.

**To Reproduce**
1. start .vue app
2. click on scan 
3. Scan page opens but home button remains pressed
4. pressing "scan" again changes the color 

**Expected behavior**
Button color should change immediately upon pressing "scan". 

**Screenshots**
<img width="378" alt="image" src="https://user-images.githubusercontent.com/69970159/107157900-f280e600-6986-11eb-9ae9-00dd797073b6.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 6

**Comment by lukasbach00** [comment]
Problem lies within the v-on:click function. Without the routing included the component works as it should.

**Comment by lukasbach00** [comment]
Solved by using a diffrent routing pattern. The component now works how it should.

**Comment by Madhour** [comment]
Now the clicked button as well as the home button are shown as clicked: 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/69970159/107446062-f5720700-6b3d-11eb-9ee8-1c456eed2c9d.png">

**Comment by lukasbach00** [comment]
fixed
