### ISSUE TITLE
dynamic v-card

### ISSUE THREAD

**Issue by BennerLukas** [BennerLukas/Tracer#27]
red or green -> 

risk -> checkRisk()
status -> localbase variable (TracerDB)
last check -> new Date() last time refresh button clicked

**Comment by Madhour** [comment]
Added dynamic value change. 
Colorchange is still open!

**Comment by lukasbach00** [comment]
Function seems to work:
risk_calculation(){
      if(this.status == "Infiziert"){
        document.getElementById("risk").style.color = '#bc1200'
      }
      else{
        document.getElementById("risk").style.color = '#287A42'
      }
    },
but the card does not change the css atm. Changes are commited.

**Comment by lukasbach00** [comment]
Card changes color depending on the risk status as it should do.
