### ISSUE TITLE
Fix Camera on mobile devices

### ISSUE THREAD

**Issue by Madhour** [BennerLukas/Tracer#52]

**Comment by Pr0lin-cyber** [comment]
Nicht genug Infos, bitte ausführen

**Comment by Madhour** [comment]
@Pr0lin-cyber Wie bereits vergangenen Sonntag besprochen - die Kamerafunktion zum Scannen funktioniert auf Mobilgeräten (beim öffnen der App als PWA) nicht. 
Evtl. wird das QRcodeStream-Modul auf den getesteten Geräten nicht unterstützt (vgl. Browser Support in den [docs](https://gruhn.github.io/vue-qrcode-reader/api/QrcodeStream.html)).

Hast du es schon auf deinem Handy ausprobiert?

**Comment by Pr0lin-cyber** [comment]
Die Library lässt es nicht zu die Kamera in bestimmten Browsern als PWA zu öffnen.
Wir waren nicht in der Lage das Problem in angemessener Zeit zu beheben.
